/* eslint-disable import/no-anonymous-default-export */
export default [
    {
       id:0,
       img:'/Lak/img5.jpg',
       name:'Wild Silk Finish Lipstick',
       price:41.0,
       category:'["lipsticks"]',
       sale:false, 
    },
    {
        id:1,
        img:'/Lak/img1.jpg',
        name:'Wild Silk Finish Lipstick',
        price:41.0,
        category:'["lipsticks"]',
        sale:false, 
     },
     {
        id:2,
        img:'/Lak/img7.jpg',
        name:'Wild Silk Finish Lipstick',
        price:41.0,
        category:'["lipsticks"]',
        sale:false, 
     },
     {
        id:3,
        img:'/Lak/img5.jpg',
        name:'Wild Silk Finish Lipstick',
        price:41.0,
        category:'["lipsticks"]',
        sale:false, 
     },
     {
        id:4,
        img:'/Lak/img4.jpg',
        name:'Wild Silk Finish Lipstick',
        price:41.0,
        category:'["lipsticks"]',
        sale:true, 
     },
     {
        id:5,
        img:'/Lak/img3.webp',
        name:'Wild Silk Finish Lipstick',
        price:41.0,
        category:'["lipsticks"]',
        sale:false, 
     },
     {
        id:6,
        img:'/Lak/img2.png',
        name:'Wild Silk Finish Lipstick',
        price:41.0,
        category:'["lipsticks"]',
        sale:true, 
     },
     {
        id:7,
        img:'/Lak/img6.jpg',
        name:'Wild Silk Finish Lipstick',
        price:41.0,
        category:'["lipsticks"]',
        sale:false, 
     },
     {
        id:8,
        img:'/Shampoo/img1.jpg',
        name:'Wild Silk Finish Lipstick',
        price:41.0,
        category:'["lipsticks"]',
        sale:true, 
     },
     {
        id:9,
        img:'/Shampoo/img2.webp',
        name:'Wild Silk Finish Lipstick',
        price:41.0,
        category:'["lipsticks"]',
        sale:false, 
     },
     {
        id:10,
        img:'/Shampoo/img3.webp',
        name:'Wild Silk Finish Lipstick',
        price:41.0,
        category:'["lipsticks"]',
        sale:true, 
     },
     {
        id:11,
        img:'/Shampoo/img4.png',
        name:'Wild Silk Finish Lipstick',
        price:41.0,
        category:'["lipsticks"]',
        sale:true, 
     },
     {
        id:12,
        img:'/Shampoo/img5.jpg',
        name:'Wild Silk Finish Lipstick',
        price:41.0,
        category:'["lipsticks"]',
        sale:false, 
     },
     {
        id:13,
        img:'/Shampoo/img6.jpg',
        name:'Wild Silk Finish Lipstick',
        price:41.0,
        category:'["lipsticks"]',
        sale:true, 
     },
     {
        id:15,
        img:'/Shampoo/img7.avif',
        name:'Wild Silk Finish Lipstick',
        price:41.0,
        category:'["lipsticks"]',
        sale:false, 
     },
     {
        id:16,
        img:'/Shampoo/img8.jpg',
        name:'Wild Silk Finish Lipstick',
        price:41.0,
        category:'["lipsticks"]',
        sale:true, 
     },
     {
      id:17,
      img:'/Tuj/img1.webp',
      name:'Wild Silk Finish Lipstick',
      price:41.0,
      category:'["lipsticks"]',
      sale:true, 
   },
   {
      id:18,
      img:'/Tuj/img2.webp',
      name:'Wild Silk Finish Lipstick',
      price:41.0,
      category:'["lipsticks"]',
      sale:true, 
   },
   {
      id:19,
      img:'/Tuj/img3.webp',
      name:'Wild Silk Finish Lipstick',
      price:41.0,
      category:'["lipsticks"]',
      sale:true, 
   },
   {
      id:20,
      img:'/Tuj/img4.webp',
      name:'Wild Silk Finish Lipstick',
      price:41.0,
      category:'["lipsticks"]',
      sale:false, 
   },
   {
      id:21,
      img:'/Tuj/img5.jpg',
      name:'Wild Silk Finish Lipstick',
      price:41.0,
      category:'["lipsticks"]',
      sale:true, 
   },
   {
      id:22,
      img:'/Tuj/img6.jpg',
      name:'Wild Silk Finish Lipstick',
      price:41.0,
      category:'["lipsticks"]',
      sale:true, 
   },
   {
      id:23,
      img:'/Tuj/img7.jpg',
      name:'Wild Silk Finish Lipstick',
      price:41.0,
      category:'["lipsticks"]',
      sale:false, 
   },
   {
      id:24,
      img:'/Tuj/img8.jpg',
      name:'Wild Silk Finish Lipstick',
      price:41.0,
      category:'["lipsticks"]',
      sale:false, 
   },
]